### PR TITLE
make a package

### LINKED ISSUE #2: create a package
great package. I would like to use it. Would mind packaging this?

once its a package on github with `setup.py`, I could install this via `pip install git+http...dataBrewery.git`. Also you can run CI with travis and get testing on a different machine.

my workaround, which isnt working:
```
!git clone https://github.com/luke-gregor/dataBrewery.git
import os
os.chdir('dataBrewery')
import databrewery as db
!pwd
cb = db.Brewery(config_file='./databrewery/config.py')
...
ScannerError: mapping values are not allowed here
  in "./databrewery/config.py", line 7, column 34
```

### PR DESCRIPTION
**Pull request by aaronspring**
- make installable with `python setup.py install`
- add development environment
- add pre-commit for linting

I am still new to databrewery. I didnt really get it running before either. Should the notebook work?

To get CI running you would need to allow https://github.com/marketplace/travis-ci which is for free for open-source projects.

closes #2

### CODE REVIEW

**Comment by lukegre** [comment]
This would be great! I've not done any CI stuff yet. Would you be able to implement this? I've added you as a member of the project.

**Comment by lukegre** [comment]
I've also been working on the master branch up until now. I've made a dev branch. Neither work smoothly, so probably not really a point at this moment 😏

**Comment by aaronspring** [comment]
notify me once this works neatly. I can be the external testing person

**Comment by lukegre** [comment]
thanks! Running smoothly now 🤞 Would be great if you could give it a go. 
I've got the testing running on Travis-CI, but the downloading, it seems, doesn't run on on the Travis-CI server. It does pass the tests locally.

**Comment by lukegre** [comment]
Also! thanks for adding all of this. Took a while to get the hang of but so nice to finally learn CI, pre-commit and pytest.

**Pull request merged**
